### ISSUE TITLE
Google Billing Need Discovered in G-Cloud Shell

### ISSUE THREAD

**Issue by MarcusSorealheis** [lucidworks/streams#44]
I did not know billing needed to be enabled to spin up a stream project until I had gotten a few steps in. It's not a difficult error to read, but I would like to know it up front so I can get that out the way and cruise. 

I suppose you mention it at the bottom of the `README` but I did not get down there until I completed the preceding instructions.

Can you put it up front?

**Comment by kordless** [comment]
Hello Marcus. 

I'm looking through the older streams projects now, can you please clarify which one it is by linking to the repo? Thanks!

**Comment by kordless** [comment]
Sorry for the delay. I've never been very prompt on getting back, but I do try to follow up. Thanks to you for responding promptly.

I don't think at the time we intend on supporting others running the buttons project directly. It is there for knowledge of what is being used, as a service, if anything. See #37 for context of what that will look like.

I would note the very first version of this debuted at Splunk's first developer conference using AWS. ;)

I like Open Source because it gives transparency. That said, I'm OK with some of it being that car that only starts for the owner. Ping me if you need help setting it up!

**Comment by MarcusSorealheis** [comment]
No worries on the delay and that all makes sense. I was referring only to the fact that I did not know I needed billing enabled in my google cloud account to spin up a stream. Some people might not pick it up from the terminal so we can call it out earlier in the documentation/README. Maybe it’s there and I just missed it. If that’s the case, we can close this issue.

**Comment by MarcusSorealheis** [comment]
Also, if we don’t intend on supporting others running buttons directly my issue definitely does not matter and can be closed.

**Comment by kordless** [comment]
Thank you!
